name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Build
      run: |
          rustup target add wasm32-wasip1
          cargo build --release --target wasm32-wasip1
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: zed-windows
        path: ${{ github.workspace }}/target/release 
