name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Enable Long File Paths
      run: git config --global core.longpaths true
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Build
      run: |
          rustup target add x86_64-pc-windows-msvc
          rustup target add wasm32-wasip1
          cargo build --release --target x86_64-pc-windows-msvc
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: zed-windows
        path: ${{ github.workspace }}/target/release 
