name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Enable Long File Paths
      run: git config --global core.longpaths true
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
    - name: Build
      env:
          RUSTFLAGS: "--cfg gles"
      run: |
          rustup toolchain install stable --profile minimal --no-self-update
          rustup target add wasm32-wasip1
          cargo build --release 
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: zed-windows
        path: ${{ github.workspace }}/target/release/zed.exe
